import type { JobResult } from '../shared/types'

const MAX_PARALLEL = 5

type JobType = 'extract' | 'writeback'

interface PendingJob {
  jobId: number
  name: string
  runId: string   // pre-generated so the renderer can match job:complete events
  startFn: () => Promise<unknown>
  resolve: (result: unknown) => void
  reject: (err: Error) => void
}

export interface ExternalJobEvent {
  event: 'queued' | 'started'
  type: JobType
  jobId: number
  runId?: string  // present on 'started' events so the renderer can track by runId
}

type ExternalJobListener = (e: ExternalJobEvent) => void

class JobScheduler {
  private extractRunning = new Map<number, string>()   // jobId → runId
  private writebackRunning = new Map<number, string>()
  private extractQueued = new Set<number>()            // jobIds waiting in the pending queue
  private writebackQueued = new Set<number>()
  private extractPending: PendingJob[] = []
  private writebackPending: PendingJob[] = []
  private completions = new Map<string, { resolve: (r: JobResult) => void }>()
  private externalListeners: ExternalJobListener[] = []

  private getRunning(type: JobType): Map<number, string> {
    return type === 'extract' ? this.extractRunning : this.writebackRunning
  }

  private getQueued(type: JobType): Set<number> {
    return type === 'extract' ? this.extractQueued : this.writebackQueued
  }

  private getPending(type: JobType): PendingJob[] {
    return type === 'extract' ? this.extractPending : this.writebackPending
  }

  private emit(e: ExternalJobEvent): void {
    for (const l of this.externalListeners) {
      l(e)
    }
  }

  onExternalEvent(listener: ExternalJobListener): () => void {
    this.externalListeners.push(listener)
    return () => {
      this.externalListeners = this.externalListeners.filter((l) => l !== listener)
    }
  }

  isRunningOrQueued(type: JobType, jobId: number): boolean {
    return this.getRunning(type).has(jobId) || this.getQueued(type).has(jobId)
  }

  // Called by startExtractRun / startWritebackRun to register a job that has started.
  registerRun(type: JobType, jobId: number, runId: string): void {
    this.getRunning(type).set(jobId, runId)
  }

  // Returns a promise that resolves when notifyComplete is called for this runId.
  // Called by startExtractRun / startWritebackRun before starting the fire-and-forget IIFE.
  awaitCompletion(runId: string): Promise<JobResult> {
    return new Promise((resolve) => {
      this.completions.set(runId, { resolve })
    })
  }

  // Must be called alongside every send('job:complete', result) in ipc-handlers.ts.
  notifyComplete(result: JobResult): void {
    const c = this.completions.get(result.runId)
    if (c) {
      this.completions.delete(result.runId)
      c.resolve(result)
    }
    // Remove from the running map (search by runId since the map is keyed by jobId)
    const running = this.getRunning(result.type as JobType)
    for (const [jobId, runId] of running) {
      if (runId === result.runId) {
        running.delete(jobId)
        break
      }
    }
    this._dequeue(result.type as JobType)
  }

  // Script path: schedule a job by jobId/name. runId must be pre-generated by the
  // caller so the same value is used in startFn and in the external event sent to
  // the renderer (allowing it to match job:complete events by runId).
  async schedule<T>(
    type: JobType,
    jobId: number,
    name: string,
    runId: string,
    startFn: () => Promise<T>
  ): Promise<T> {
    if (this.isRunningOrQueued(type, jobId)) {
      const kind = type === 'extract' ? 'Download' : 'Writeback'
      throw new Error(`${kind} job "${name}" is already queued or running`)
    }
    if (this.getRunning(type).size < MAX_PARALLEL) {
      this.emit({ event: 'started', type, jobId, runId })
      return startFn()
    }
    // At capacity — queue it
    this.getQueued(type).add(jobId)
    this.emit({ event: 'queued', type, jobId })
    return new Promise<T>((resolve, reject) => {
      this.getPending(type).push({
        jobId,
        name,
        runId,
        startFn: startFn as () => Promise<unknown>,
        resolve: resolve as (r: unknown) => void,
        reject
      })
    })
  }

  private _dequeue(type: JobType): void {
    const pending = this.getPending(type)
    if (pending.length === 0 || this.getRunning(type).size >= MAX_PARALLEL) {
      return
    }
    const next = pending.shift()!
    this.getQueued(type).delete(next.jobId)
    this.emit({ event: 'started', type, jobId: next.jobId, runId: next.runId })
    next.startFn().then(next.resolve).catch(next.reject)
  }
}

export const scheduler = new JobScheduler()
